import type { Metadata } from 'next'
import './globals.css'

import RootWrapper from '@/components/RootWrapper'

export const metadata: Metadata = {
  title: 'Qoyyid',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" dir="auto">
      <body className="font-sans text-qoyyid-black"><RootWrapper>{children}</RootWrapper></body>
    </html>
  )
}
